test/integration.sh

This branch fixes a syntax error in `test/integration.sh`.

Add missing brace in integration.sh

---

test/fixtures/automatic_labelling/README.md

This branch moves the autogenerated docs in the fixture `README.md` for consistency.

Move autogenerated docs to precede Requirements

---

Makefile
test/make.sh

This project does not contain any Go files or Dockerfiles.

Remove check_golang, check_docker

---

.gitignore
test/fixtures/automatic_labelling/terraform.tfvars
test/integration.sh

This branch ignores the erroneously included `terraform.tfvars`.

Ignore terraform.tfvars

---

README.md
examples/automatic_labelling/README.md
examples/automatic_labelling/main.tf
examples/automatic_labelling/variables.tf
test/fixtures/automatic_labelling/main.tf
test/integration.sh

This branch updates integration.sh to use the standardized logic from other modules.

Update integration.sh to use standardized logic

---

examples/delete-vms-without-cmek/README.md
examples/delete-vms-without-cmek/function_source/cmek.go
examples/delete-vms-without-cmek/function_source/go.mod
examples/delete-vms-without-cmek/main.tf
examples/delete-vms-without-cmek/variables.tf

This Cloud Function detects newly created VM Instances that have disks attached
with a Google-managed encryption key attached and then immediately deletes
any such VM instances.

Add Cloud Function that deletes VM instances created without CMEK.

---

main.tf

For the GCS bucket created to store the Cloud Function, always use uniform-level bucket access. Right now if this configuration is controlled via an org policy, you can't use this module - there are no other workarounds.
```
Error: googleapi: Error 412: Request violates constraint 'constraints/storage.uniformBucketLevelAccess', conditionNotMet
on .terraform/modules/firestore-export/main.tf line 50, in resource "google_storage_bucket" "main":
50: resource "google_storage_bucket" "main" {
```

Use uniform-level access policy in GCS bucket

---

README.md
main.tf
variables.tf

Supports a scenario where function archive sources are place on an existing bucket.

Adds option to use an existing archive bucket

---

README.md
main.tf
variables.tf

Adding `ingress_settings` variable to the Cloud Function.  A customer requested this for security purposes.

Add Ingress Settings to the Function

---

main.tf

Remove `bucket_policy_only` as it is deprecated and replace with `uniform_bucket_level_access`

fix: Remove bucket_policy_only, add uniform_bucket_level_access

---

CHANGELOG.md
versions.tf

Similar to https://github.com/terraform-google-modules/terraform-google-cloud-storage/pull/84

fix: constrain minimum Google provider version to 3.38

---

main.tf

Removed the interpolation expression because it was popping up a warning when running with terraform >=12.
Fixes #53.

removed interpolation expression

---

README.md
main.tf
variables.tf

Adding `vpc_connector` support for the Cloud Function. This should resolve #55

Add Serverless VPC Connector support for the Cloud Function

---

README.md
main.tf
variables.tf

1. Exposes max_instances on the google_cloudfunctions_function.
- Defaulted to 0, resulting in a noop for existing instances where the input is omitted.
- Setting is useful for resolving API or application throttling issues due to high execution rates.
2. Corrects string substitution syntax, deprecated in terraform 0.13+
3. Updates docs.

Adds optional input 'max_instances'

---

README.md
main.tf
variables.tf

Hey folks!
This pull request closes #67 issue.
Could you, please, take a look on it?
Thanks!

Adds support to excludes parameter

---

README.md
main.tf
outputs.tf
variables.tf

This PR is adding an extra input called `trigger_http` which allows to create a function which is triggered by any HTTP request. This makes the previously required input `event_trigger` optional as only one of them can be used at a time.

Adding trigger_http input

---

modules/repository-function/README.md
modules/repository-function/main.tf
modules/repository-function/variables.tf

Update repository-function module to support VPC connector, VPC connector egress, and ingress settings.

Update repository-function module to support VPC connector

---

README.md
examples/dynamic-files/README.md
examples/dynamic-files/function_source/index.js
examples/dynamic-files/main.tf
examples/dynamic-files/outputs.tf
examples/dynamic-files/versions.tf
main.tf
test/integration/dynamic-files/dynamic_files_test.go
test/setup/iam.tf
test/setup/main.tf
variables.tf
versions.tf

Hello All,
I would like to add support for using secret manager environment variables to this module.
New variable: `secret_environment_variables`
Supported by Google provider since version 4.11.0
Available for Terraform >= v0.13.0
Example of usage:
```
module "http_function" {
source  = "terraform-google-modules/event-function/google"
...
secret_environment_variables = [
{
key        = "ACCESS_TOKEN"
project_id = "111111"
secret     = "SECRET_ACCESS_TOKEN"
},
{
key     = "CLIENT_ID"
secret  = "SECRET_CLIENT_ID"
version = "1"
}
]
...
}
```

Add support for using secret manager environment variables in Cloud Function

---

README.md
main.tf
variables.tf

This adds the capability to pass build time environment variables such as GOOGLE_FUNCTION_SOURCE.

feat: add support for setting build environment variables

---

examples/automatic-labelling-folder/main.tf
examples/automatic-labelling-from-localhost/main.tf
examples/automatic-labelling-from-repository/main.tf
examples/delete-vms-without-cmek/main.tf
examples/dynamic-files/main.tf
modules/repository-function/README.md
modules/repository-function/main.tf
modules/repository-function/variables.tf
test/setup/versions.tf

workaround for https://github.com/hashicorp/terraform-provider-google/issues/13263

fix: set optional max_instances to default value for CI

---

main.tf

The gzip content encoding is not right for a zip archive and does not
actually work. When working with this module, I had to remove the
content-encoding to make things work. Otherwise, I was getting a
"End-of-central-directory signature not found" error in Cloud Build
during function deployment.
When I tried to download the archive using my browser, the browser
errored, but gsutil succeeded. The file uploaded to GCS was complete so
that was not the reason for the error. Removing the content-encoding
field fixed the deployment.

fix: remove gzip content-encoding metadata on function source archive 
